### PR TITLE
feature: Add amazon-sagemaker-jupyter-ai-q-developer and others

### PR DESCRIPTION
**Pull request by kumarnzt**
Add amazon-sagemaker-jupyter-ai-q-developer and others amazon-q-developer-jupyterlab-ext.

*Issue #, if available:*

*Description of changes:*
Adding new dependencies and bumping others as follows:

1.    amazon-sagemaker-jupyter-ai-q-developer[version='>=1.0.3,<2.0'] - new extension

2.    amazon-q-developer-jupyterlab-ext[version='>=3.1.0,<4.0'] - new extension for CW

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bhadrip — APPROVED** [review]

**Comment by claytonparnell** [comment]
Can you please add unit tests for these packages?

**Comment by kumarnzt** [comment]
Added tests for new packages.

**Comment by dylanraws** [comment]
I see the tests simply import the packages. Is it possible to test one or more actual features of these packages? In the event that another change in the image affects deeper functionality of these new packages, a simple import may not catch that.

**Comment by TRNWWZ** [comment]
Why is `amazon_codewhisperer_jupyterlab_ext` removed from the unit test, is it no longer used?

**Comment by kumarnzt** [comment]
> Why is `amazon_codewhisperer_jupyterlab_ext` removed from the unit test, is it no longer used?

Yes, `amazon_codewhisperer_jupyterlab_ext` is no longer used and needs to be removed. `amazon-q-developer-jupyterlab-ext` is a replacement for it which is added.

**Comment by kumarnzt** [comment]
> I see the tests simply import the packages. Is it possible to test one or more actual features of these packages? In the event that another change in the image affects deeper functionality of these new packages, a simple import may not catch that.

Testing functional features require getting the AmazonQ SSO credentials (to be able to make chat calls). We should be good with these now to confirm that SMD is not breaking, I will take a look at feasibility for extension functionality testing separately.

**Review by TRNWWZ — APPROVED** [review]

**Review by dylanraws — APPROVED** [review]

**Pull request merged**
