### PR TITLE
Adding langchain

### PR DESCRIPTION
**Pull request by 3coins**
*Issue #, if available:* NA

*Description of changes:*
Adding `langchain` to the distribution.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by 3coins** [comment]
@balajisankar15 
I am getting an error while building. `networkx` is an optional dependency of LangChain, is there anything I can do to fix this?

```
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ autogluon >=0.8.2,<0.9.0  is installable with the potential options
    │  ├─ autogluon 0.8.2 would require
    │  │  └─ autogluon.core ==0.8.2 *light*, which does not exist (perhaps a missing channel);
    │  └─ autogluon 0.8.2 would require
    │     └─ autogluon.timeseries 0.8.2  with the potential options
    │        ├─ autogluon.timeseries 0.8.2 would require
    │        │  └─ pandas >=1.4.1,<1.6  with the potential options
    │        │     ├─ pandas [1.4.1|1.4.2|...|2.0.3] would require
    │        │     │  └─ python_abi 3.10.* *_cp310, which can be installed;
    │        │     ├─ pandas [1.4.1|1.4.2|...|1.5.3], which can be installed;
    │        │     ├─ pandas [1.4.1|1.4.2|...|2.0.3] would require
    │        │     │  └─ python_abi 3.9.* *_cp39, which can be installed;
    │        │     ├─ pandas [1.4.2|1.4.3|...|2.0.3] would require
    │        │     │  └─ python_abi 3.8 *_pypy38_pp73, which can be installed;
    │        │     ├─ pandas [1.4.2|1.4.3|...|2.0.3] would require
    │        │     │  └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
    │        │     └─ pandas [1.5.1|1.5.2|1.5.3|2.0.3] would require
    │        │        └─ python_abi 3.11.* *_cp311, which can be installed;
    │        └─ autogluon.timeseries 0.8.2 would require
    │           └─ networkx >=3.0,<4 , which can be installed;
    ├─ langchain >=0.0.277,<0.1.0  is not installable because it requires
    │  └─ networkx >=2.6.3,<3.0.0 , which conflicts with any installable versions previously reported;
    ├─ pandas >=2.0.3,<2.1.0  is installable with the potential options
    │  ├─ pandas [1.4.1|1.4.2|...|2.0.3], which can be installed (as previously explained);
    │  ├─ pandas [1.4.1|1.4.2|...|2.0.3], which can be installed (as previously explained);
    │  ├─ pandas [1.4.2|1.4.3|...|2.0.3], which can be installed (as previously explained);
    │  ├─ pandas [1.4.2|1.4.3|...|2.0.3], which can be installed (as previously explained);
    │  ├─ pandas [1.5.1|1.5.2|1.5.3|2.0.3], which can be installed (as previously explained);
    │  └─ pandas 2.0.3 conflicts with any installable versions previously reported;
    ├─ python >=3.8.17,<3.9.0  is not installable because it requires
    │  └─ python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
    ├─ pytorch-gpu >=2.0.0,<2.1.0  does not exist (perhaps a typo or a missing channel);
    └─ tensorflow >=2.12.1,<2.13.0  does not exist (perhaps a typo or a missing channel).
```

**Comment by balajisankar15** [comment]
Can we submit a pull request to Langchain to update networkx if it is an easy change ? Because having a strict upper bound will bite us in the future.

Note: If that is merged, you need to submit another PR to update the dependencies in the conda forge feedstock. https://github.com/conda-forge/langchain-feedstock/blob/main/recipe/meta.yaml#L81

**Comment by 3coins** [comment]
@balajisankar15 
Moving from 2.x to 3.x will have breaking changes, my sense is that this is not going to be a trivial task, as we will likely need updates to the affected code in LangChain, which we don't own, so might need approval from the `networkx` owners, delaying release. This will also have a recursive effect on some other packages that depend on `langchain`, for example `jupyter-ai` that will need to be updated to use the latest langchain version and will need testing around that.

In case we we are not able to get this updated, is there a workaround to handle this case?

**Comment by 3coins** [comment]
cc @ellisonbg

**Comment by 3coins** [comment]
Closing this as `langchain` is being pulled in by `jupyter-ai`, which has been merged by PRs #77 and #84.

**Pull request closed without merging**
