### PR TITLE
Fixes for checkstyle

### PR DESCRIPTION
**Pull request by kumarnzt**
*Issue #, if available:*

*Description of changes:*
No logic changes, fixing the files based on the recommended checkstyle.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by balajisankar15** [comment]
Approving . @nikhilumeshsargur  will fix the "isort" checkstyle for v2 tests as part of a different PR

**Comment by balajisankar15** [comment]
Or you can simply copy the run_pandas_test.py from v1 to v2?

**Comment by kumarnzt** [comment]
Pasted the import order from v1 to v2 in recent commit. isort is not giving any error now.

**Review by balajisankar15 — APPROVED** [review]

**Review by nikhilumeshsargur — APPROVED** [review]
Approving the change

**Pull request merged**
